### ISSUE TITLE
Feature Request: a toggle between pessimism and optimism using lax-steps with reductions

### ISSUE THREAD

**Issue by shadowbourne** [janosh/tensorboard-reducer#9]
I believe as general practice having the reduction cut off at the lowest step count is a good idea.
However I also believe that there are some cases in which it would be very helpful to be able to be able to cut off the averaging at the highest step count i.e. optimistic, 
Thus a switch option for this would be very helpful
, or potentially an integer input for the minimum number of remaining runs at which to cut off and stop averaging, however this would obviously be more work.

Let me know what you think.

**Comment by janosh** [comment]
Thanks for the suggestion. I need to think about this. My worry is having the ability to average variable number of runs depending on how many are available, i.e. changing the statistics of a reduction mid-run, would facilitate bad behavior. Imagine a low-quality ML paper not mentioning that their statistical significance testing for whatever performance improvements they claim dropped from 10 to 4 samples mid-plot. 

Also need to work on a presentation for tomorrow but should have time to come back to this later next week.

**Comment by janosh** [comment]
So I'm still not sure this is a good idea but someone smarter than me _does_ think so. You have @CompRhys to thank for convincing me to implement this feature. 😄 

[Released in v0.2.3](https://pypi.org/project/tensorboard-reducer/0.2.3) is a new CLI flag called `--min-runs-per-step` that should do what you need. Let me know if it's working for you.

**Comment by janosh** [comment]
Will close this as assumed fixed. Feel free to reopen if issues remain.
